###! jQuery Scroll Snap 1.0.0 | MIT *
# https://github.com/jpcurrier/jquery-scroll-snap !
###

(($) ->

  $.fn.scrollSnap = (options) ->
    # default options
    settings = $.extend({ speed: 400 }, options)
    scrollStop = undefined
    lastScrollTop = window.pageYOffset or document.documentElement.scrollTop or document.body.scrollTop or 0
    $snap = this
    snapScroll = ($snap, scroll, direction) ->
      if $('body').hasClass('lock-scroll')
        return
      windowHeight = $('.viewport').height()
      direction = if typeof direction != 'undefined' then direction else 'up'
      scrollTo = false
      video = $($snap).find 'video'
      video.trigger 'pause'
      $snap.each -> 
        distance = $(this).offset().top + $(".viewport").scrollTop()
        # margin = $(this).outerHeight(true) - $(this).outerHeight(false)
        margin = parseInt($(this).css 'margin-bottom')
        if scroll <= distance and (direction == 'down' and scroll >= distance - (windowHeight / 2) - margin or direction == 'up' and scroll >= distance - (windowHeight / 2) - margin) or scroll >= distance and (direction == 'up' and scroll <= distance + windowHeight  / 2 + margin or direction == 'down' and scroll <= distance + windowHeight / 2 + margin )
          $('body:not( .lock-scroll )').addClass 'lock-scroll'
          scrollTo = distance
          video = $(this).find 'video'
          video.trigger 'play'
        return
      if scrollTo != false
        $('.viewport').animate { scrollTop: scrollTo }, settings.speed, ->
          # $('body.lock-scroll').removeClass 'lock-scroll'
          setTimeout ( ->
            $( 'body.lock-scroll' ).removeClass( 'lock-scroll' )
          ), 600 
          return
      return

    $('.viewport').on 'scroll', ->
      scroll = $('.viewport').offset().top or document.documentElement.scrollTop or $('.viewport').scrollTop() or 0
      direction = 'up'
      if scroll > lastScrollTop
        direction = 'down'
      lastScrollTop = scroll
      clearTimeout scrollStop
      scrollStop = setTimeout((->
        snapScroll $snap, scroll, direction
        return
      ), 200)
      return
    return

  return
) jQuery

# ---
# generated by js2coffee 2.2.0